# Generated by Django 3.1.6 on 2021-04-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sesrch',
            new_name='Search',
        ),
    ]
